service: tradle-messaging
frameworkVersion: ">=1.5.0 <2.0.0"

plugins:
  - serverless-resources-env
  # - serverless-dynamodb-ttl
  # - serverless-plugin-write-env-vars
  # - serverless-plugin-include-dependencies
  # - serverless-dynamodb-local
  # - serverless-offline

package:
  exclude:
    - .git/**
    - .serverless/**
    - scripts/**
    - node_modules/**
    - simulate/**
    - garbage/**
    - ./**/*.log

custom:
  prefix: ${{self:service}}-${{self:provider.stage}}-
  defaultStage: dev
  stage: ${{opt:stage, self:custom.defaultStage}}
  accountId: ${{file(./env.json):ACCOUNT_ID}}
  NETWORK_NAME: testnet
  METADATA_PREFIX: ${{file(./project/lib/constants.json):METADATA_PREFIX}}
  IDENTITY_KEYS_KEY: ${{file(./project/lib/constants.json):IDENTITY_KEYS_KEY}}
  SECRETS_BUCKET: ${{self:custom.prefix}}secrets
  OBJECTS_BUCKET: ${{self:custom.prefix}}objects
  PRIVATE_CONF_BUCKET: ${{self:custom.prefix}}private-conf
  PUBLIC_CONF_BUCKET: ${{self:custom.prefix}}public-conf
  props:
    author: ${{self:custom.METADATA_PREFIX}}author
    recipient: ${{self:custom.METADATA_PREFIX}}recipient
    seq: seq
  # writeEnvVars:
  #   SERVERLESS_STAGE: ${{self:custom.stage}}
  #   SERVERLESS_SERVICE_NAME: ${{self:service}}
  #   SERVERLESS_PREFIX: ${{self:service}}-${{self:provider.stage}}

#   secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}
  # deployBucket: io.tradle.aws.code
  # dynamodb:
  #   start:
  #     port: 8000
  #     inMemory: true
  #     migration: true
  #   migration:
  #     dir: offline/migrations

provider:
  variableSyntax: '\${{([\s\S]+?)}}'
  # variableSyntax: "\${{([\s\S]+?)}}"
  name: aws
  runtime: nodejs6.10
  profile: serverless
  stage: ${{self:custom.stage}}
  region: us-east-1
  pushServer: https://push1.tradle.io
  memorySize: 128
  # deploymentBucket: io.tradle.${{self:provider.region}.deploys # Overwrite the default deployment bucket
  environment:
    NETWORK_NAME: testnet
    DEBUG: tradle:*
    SERVERLESS_STAGE: ${{self:custom.stage}}
    SERVERLESS_SERVICE_NAME: ${{self:custom.stage}}
    PUSH_SERVER_URL: ${{self:custom.pushServer}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/EventsTable"
        # - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/MessagesTable"
        - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/PresenceTable"
        - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/InboxTable"
        - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/OutboxTable"
        - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/PubKeysTable"
        - "arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/PubKeysTable/index/permalink"

    # allow access to bucket
    # TODO: give access only to the lambdas that need it
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::${{self:custom.OBJECTS_BUCKET}}/*"
        - "arn:aws:s3:::${{self:custom.SECRETS_BUCKET}}/*"

    # REMOVE in prod
    # allow access to buckets from the console
    - Effect: Allow
      Action:
        - s3:GetBucketLocation
        - s3:ListAllMyBuckets
      Resource: "arn:aws:s3:::*"

    # allow lambdas to call each other
    # TODO: make this more fine grained
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

    # Iot
    - Effect: Allow
      Action: ["iot:Connect", "iot:Subscribe", "iot:Publish", "iot:Receive", "iot:DescribeEndpoint"]
      Resource: ["*"]

    # gen Iot temp credentials (lambda: preauth)
    - Effect: "Allow"
      Action:
        - sts:AssumeRole
      Resource: "*"

      # Resource: "*"
   # - Effect: "Allow"
   #   Action:
   #     - "s3:GetObject"
   #   Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
   # - Effect: "Allow"
   #   Action:
   #     - "s3:PutObject"
   #   Resource:
   #     Fn::Join:
   #       - ""
   #       - - "arn:aws:s3:::"
   #         - "Ref" : "ServerlessDeploymentBucket"
   #         - "/*"

functions:
  preauth:
    handler: project/lib/lambda/preauth.handler
    memorySize: 1024
    events:
      - http:
          path: tradle/preauth
          method: post
          cors: true
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - ObjectsBucket
        - EventsTable
        - PresenceTable
        - PubKeysTable
        - InboxTable
        - OutboxTable
        - IotClientRole
  auth:
    handler: project/lib/lambda/auth.handler
    memorySize: 1024
    events:
      - http:
          path: tradle/auth
          method: post
          cors: true
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - ObjectsBucket
        - EventsTable
        - PresenceTable
        - PubKeysTable
        - InboxTable
        - OutboxTable
        - IotClientRole
  createevent:
    handler: project/lib/lambda/createevent.handler
    memorySize: 512

  log:
    handler: project/lib/lambda/log.handler
    # package:
    #   exclude:
    #     - node_modules/
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - SecretsBucket
        - ObjectsBucket
        - PresenceTable
        - EventsTable
        - PubKeysTable
        - InboxTable
        - OutboxTable

    # events:
  #     - stream:
  #         type: dynamodb
  #         batchSize: 20
  #         startingPosition: TRIM_HORIZON
  #         arn:
  #           Fn::GetAtt:
  #             - EventsTable
  #             - StreamArn

  # fanout:
  #   handler: project/lib/lambda/fan-out.handler
  #   memorySize: 512
  #   environment:
  #     DEBUG: tradle:*
  #     SERVERLESS_PREFIX: ${{self:custom.prefix}}
  #   custom:
  #     env-resources:
  #       - SecretsBucket
  #       - ObjectsBucket
  #       - EventsTable
  #       - PubKeysTable
  #       - InboxTable
  #       - OutboxTable
  #   events:
  #     - stream:
  #         type: dynamodb
  #         batchSize: 20
  #         startingPosition: TRIM_HORIZON
  #         arn:
  #           Fn::GetAtt:
  #             - EventsTable
  #             - StreamArn

  # onconnect:
  #   handler: project/lib/lambda/onconnect.handler
  #   events:
  #     - iot:
  #         sql: "SELECT * FROM '$aws/events/presence/connected/#'"
  #   environment:
  #     DEBUG: tradle:*

  onsubscribe:
    handler: project/lib/lambda/onsubscribe.handler
    memorySize: 1024
    events:
      - iot:
          sql: "SELECT * FROM '$aws/events/subscriptions/subscribed/#'"
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - ObjectsBucket
        - EventsTable
        - PresenceTable
        - PubKeysTable
        - InboxTable
        - OutboxTable

  restore:
    handler: project/lib/lambda/restore.handler
    memorySize: 1024
    events:
      - iot:
          sql: "SELECT * as data, topic() as topic FROM '+/restore'"
          actions:
            - lambda:

    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - ObjectsBucket
        - EventsTable
        - PresenceTable
        - PubKeysTable
        - InboxTable
        - OutboxTable

    # ondisconnect:
  #   handler: project/lib/lambda/handshake.break
  #   events:
  #     - iot:
  #         sql: "SELECT * FROM '$aws/events/presence/disconnected'"

  queuereceive:
    handler: project/lib/lambda/queuereceive.handler
    memorySize: 1024
    environment:
      DEBUG: tradle:*
    events:
      - iot:
          sql: "SELECT * FROM 'message'"
    custom:
      env-resources:
        - SecretsBucket
        - ObjectsBucket
        - EventsTable
        - PresenceTable
        - PubKeysTable
        - InboxTable
        - OutboxTable

  echo:
    handler: project/lib/lambda/echo.handler
    memorySize: 1024
    custom:
      env-resources:
        - ObjectsBucket
        - SecretsBucket
        - EventsTable
        - PresenceTable
        - PubKeysTable
        - InboxTable
        - OutboxTable
    events:
      - stream:
          type: dynamodb
          batchSize: 20
          startingPosition: TRIM_HORIZON
          arn:
            Fn::GetAtt:
              - InboxTable
              - StreamArn
    environment:
      DEBUG: tradle:*

  addcontact:
    handler: project/lib/lambda/addContact.handler
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - ObjectsBucket
        - PubKeysTable

  identity:
    handler: project/lib/lambda/identity.handler
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - SecretsBucket
        - ObjectsBucket
        - PubKeysTable

  info:
    handler: project/lib/lambda/info.handler
    environment:
      DEBUG: tradle:*
      SERVERLESS_STAGE: ${{self:custom.stage}}
      SERVERLESS_SERVICE_NAME: ${{self:custom.stage}}
    custom:
      env-resources:
        - SecretsBucket
        - ObjectsBucket
        - PubKeysTable
    events:
      - http:
          path: tradle/info
          method: get
          cors: true

  init:
    handler: project/lib/lambda/init.handler
    memorySize: 512
    environment:
      NETWORK_NAME: testnet
      DEBUG: tradle:*
    custom:
      env-resources:
        - SecretsBucket
        - ObjectsBucket
        - PubKeysTable
        - PublicConfBucket

  queuesend:
    handler: project/lib/lambda/queuesend.handler
    memorySize: 512
    environment:
      DEBUG: tradle:*
    custom:
      env-resources:
        - SecretsBucket
        - ObjectsBucket
        - EventsTable
        - PubKeysTable
        - InboxTable
        - OutboxTable

  # send:
  #   handler: project/lib/lambda/send.handler
  #   environment:
  #     DEBUG: tradle:*
  #   custom:
  #     env-resources:
  #       - SecretsBucket
  #       - ObjectsBucket
  #       - EventsTable
  #       - PubKeysTable
  #       - InboxTable
  #       - OutboxTable

  # sign:
  #   handler: project/lib/lambda/sign.handler
  #   events:
  #     - http:
  #         path: /sign
  #         method: post
  #         cors: true

  # info:
  #   handler: project/lib/lambda/info.handler
  #   events:
  #     - http:
  #         path: info
  #         method: get
  #         cors: true


    # environment:
    #   ENCRYPTION_KEY: ${{self:custom.secrets.SESSION_KEY}}
    #   EMAIL_SERVICE_API_KEY: ${{self:custom.secrets.EMAIL_SERVICE_API_KEY}}


resources:
  Resources:
    ObjectsBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${{self:custom.OBJECTS_BUCKET}}

    SecretsBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${{self:custom.SECRETS_BUCKET}}

    PrivateConfBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${{self:custom.PRIVATE_CONF_BUCKET}}

    PublicConfBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${{self:custom.PUBLIC_CONF_BUCKET}}
        AccessControl: PublicRead

    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE

    PubKeysTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PubKeysTable
        AttributeDefinitions:
          - AttributeName: pub
            AttributeType: S
          - AttributeName: permalink
            AttributeType: S
        KeySchema:
          - AttributeName: pub
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: permalink
            KeySchema:
              - AttributeName: permalink
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - link
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

    # stores metadata about incoming messages
    # bodies rot in s3
    InboxTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: InboxTable
        AttributeDefinitions:
          - AttributeName: ${{self:custom.props.author}}
            AttributeType: S
          - AttributeName: ${{self:custom.props.seq}}
            AttributeType: N
        KeySchema:
          - AttributeName: ${{self:custom.props.author}}
            KeyType: HASH
          - AttributeName: ${{self:custom.props.seq}}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    OutboxTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OutboxTable
        AttributeDefinitions:
          - AttributeName: ${{self:custom.props.recipient}}
            AttributeType: S
          - AttributeName: ${{self:custom.props.seq}}
            AttributeType: N
        KeySchema:
          - AttributeName: ${{self:custom.props.recipient}}
            KeyType: HASH
          - AttributeName: ${{self:custom.props.seq}}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES


    # stores metadata about incoming messages
    # bodies rot in s3
    # MessagesTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: MessagesTable
    #     AttributeDefinitions:
    #       - AttributeName: ${{self:custom.props.author}}
    #         AttributeType: S
    #       - AttributeName: ${{self:custom.props.recipient}}
    #         AttributeType: S
    #       - AttributeName: ${{self:custom.props.seq}}
    #         AttributeType: N
    #     # Inbox
    #     KeySchema:
    #       - AttributeName: ${{self:custom.props.author}}
    #         KeyType: HASH
    #       - AttributeName: ${{self:custom.props.seq}}
    #         KeyType: RANGE
    #     ProvisionedThroughput:
    #       ReadCapacityUnits: 5
    #       WriteCapacityUnits: 5
    #     StreamSpecification:
    #       StreamViewType: NEW_AND_OLD_IMAGES
    #     # Outbox
    #     GlobalSecondaryIndexes:
    #       - IndexName: recipient
    #         KeySchema:
    #           - AttributeName: ${{self:custom.props.recipient}}
    #             KeyType: HASH
    #           - AttributeName: ${{self:custom.props.seq}}
    #             KeyType: RANGE
    #         Projection:
    #           ProjectionType: ALL
    #         ProvisionedThroughput:
    #           ReadCapacityUnits: 5
    #           WriteCapacityUnits: 5

    # stores mappings between identity permalink and ephemeral clientIds
    # mappings are created after initial handshake and destroyed on disconnect
    PresenceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PresenceTable
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
          - AttributeName: permalink
            AttributeType: S
        KeySchema:
          - AttributeName: permalink
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    # EventsStreamEventSourceMapping:
    #   Type: AWS::Lambda::EventSourceMapping
    #   DependsOn: IamPolicyLambdaExecution
    #   Properties:
    #     BatchSize: 10
    #     EventSourceArn:
    #       Fn::GetAtt:
    #         - EventsTable
    #         - StreamArn
    #     FunctionName:
    #       Fn::GetAtt:
    #         - fanout
    #         - Arn
    #     StartingPosition: TRIM_HORIZON
    #     Enabled: True



    # IoT
    # define IoT role
    # IoTLambdaRole:
    #   Type: AWS::IAM::Role
    #   Properties:
    #     AssumeRolePolicyDocument:
    #       Version: "2012-10-17"
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             AWS: arn:aws:iam:::root
    #           Action:
    #             - sts:AssumeRole

    PushSubcribersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PushSubscribersTable
        AttributeDefinitions:
          - AttributeName: subscriber
            AttributeType: S
        KeySchema:
          - AttributeName: subscriber
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    IotClientRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: IotClientRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                AWS:
                  - arn:aws:iam::${{self:custom.accountId}}:root
                  # - arn:aws:iam::${{self:custom.accountId}}:role/${{self:custom.prefix}}${{self:provider.region}}-lambdaRole"
                  # - Fn::Join" : [":", ["arn:aws:iam", { "Ref" : "AWS::Region" }, { "Ref" : "AWS::AccountId" }, "lambdaRole" ] ] }

                # AWS: "arn:aws:iam::${{}}:role/${{self:custom.prefix}}lambdaRole"
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: IotClientRole
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:*
                  Resource:
                    - arn:aws:dynamodb:${{self:provider.region}}:${{self:custom.accountId}}:table/PresenceTable
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:::log-group:/aws/lambda/*:*:*
                # restrict client connect by client id
                - Effect: Allow
                  Action: ["iot:Connect"]
                  Resource: ["*"]
                  # Resource: ["aws:iot:::client/${iot:ClientId}/*"]
                # allow all clients to publish to the send topic
                - Effect: "Allow"
                  Action: ["iot:Publish"]
                  Resource: ["*"]
                  # Resource: [
                  #   "aws:iot:::topic/${iot:ClientId}/message",
                  #   "aws:iot:::topic/${iot:ClientId}/restore",
                  # ]
                # restrict client topic subscriptions by their client id
                - Effect: "Allow"
                  Action: ["iot:Subscribe"]
                  Resource: ["*"]
                  # Resource: ["aws:iot:::topicfilter/${iot:ClientId}/*"]
                # restrict messages clients receive by their client id
                # this has the same function as the Subscribe rule above
                # provided the Subscribe policy is upheld, this policy should always give a pass
                - Effect: "Allow"
                  Action: ["iot:Receive"]
                  Resource: ["*"]
                  # Resource: ["aws:iot:::topic/${iot:ClientId}/*"]

