service: tradle
frameworkVersion: '>=1.5.0 <2.0.0'
plugins:
  - serverless-plugin-tracing
  - serverless-sam
package:
  exclude:
    - .git/**
    - .serverless/**
    - scripts/**
    - node_modules/**
    - simulate/**
    - ./**/*.log
custom:
  defaultStage: dev
  prefix: '${{self:service}}-${{self:provider.stage}}-'
  tablePrefix: '${{self:custom.prefix}}'
  rolePrefix: '${{self:custom.prefix}}'
  topicPrefix: tradle-
  stage: '${{opt:stage, self:custom.defaultStage}}'
  region: '${{opt:region, self:provider.region}}'
  pushServer: 'https://push1.tradle.io'
  blockchain: 'bitcoin:testnet'
  bot_onmessage: bot_onmessage
  bot_onsealevent: bot_onsealevent
  bot_onpresence: bot_onpresence
  tables:
    presence: '${{self:custom.tablePrefix}}presence'
    seals: '${{self:custom.tablePrefix}}seals'
    pubkeys: '${{self:custom.tablePrefix}}pubkeys'
    inbox: '${{self:custom.tablePrefix}}inbox'
    outbox: '${{self:custom.tablePrefix}}outbox'
    events: '${{self:custom.tablePrefix}}events'
    users: '${{self:custom.tablePrefix}}users'
provider:
  versionFunctions: false
  tracing: true
  variableSyntax: '\${{([\s\S]+?)}}'
  name: aws
  runtime: nodejs6.10
  profile: serverless
  stage: '${{self:custom.stage}}'
  region: us-east-1
  memorySize: 512
  timeout: 60
  environment:
    IOT_TOPIC_PREFIX: '${{self:custom.topicPrefix}}'
    IOT_ENDPOINT: ''
    BLOCKCHAIN: '${{self:custom.blockchain}}'
    DEBUG: 'tradle:*,Î»*'
    SERVERLESS_PREFIX: '${{self:custom.prefix}}'
    SERVERLESS_STAGE: '${{self:custom.stage}}'
    SERVERLESS_SERVICE_NAME: '${{self:service}}'
    PUSH_SERVER_URL: '${{self:custom.pushServer}}'
    BOT_ONPRESENCE: '${{self:custom.bot_onpresence}}'
    BOT_ONMESSAGE: '${{self:custom.bot_onmessage}}'
    ORG_DOMAIN: tradle.io
    ORG_NAME: Tradle
    ORG_LOGO: '${{file(./env.json):LOGO_TRADLE}}'
    R_BUCKET_OBJECTS:
      Ref: ObjectsBucket
    R_BUCKET_SECRETS:
      Ref: SecretsBucket
    R_BUCKET_PUBLICCONF:
      Ref: PublicConfBucket
    R_TABLE_EVENTS:
      Ref: EventsTable
    R_TABLE_PUBKEYS:
      Ref: PubKeysTable
    R_TABLE_INBOX:
      Ref: InboxTable
    R_TABLE_OUTBOX:
      Ref: OutboxTable
    R_TABLE_SEALS:
      Ref: SealsTable
    R_TABLE_USERS:
      Ref: UsersTable
    R_TABLE_PRESENCE:
      Ref: PresenceTable
    R_ROLE_IOTCLIENT:
      Ref: IotClientRole
    R_BUCKET_SERVERLESSDEPLOYMENT:
      Ref: ServerlessDeploymentBucket
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:BatchWriteItem'
        - 'dynamodb:DescribeStream'
        - 'dynamodb:GetRecords'
        - 'dynamodb:GetShardIterator'
        - 'dynamodb:ListStreams'
      Resource:
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.events}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.presence}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.inbox}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.inbox}}/index/*
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.outbox}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.pubkeys}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.pubkeys}}/index/*
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.seals}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.seals}}/index/*
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.users}}
        - 'Fn::Sub': >-
            arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/${{self:custom.tables.users}}/index/*
    - Effect: Allow
      Action:
        - 'cloudformation:ListStackResources'
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - 'lambda:UpdateFunctionConfiguration'
        - 'lambda:GetFunctionConfiguration'
      Resource:
        - 'Fn::Sub': >-
            arn:aws:lambda:${{self:custom.region}}:${AWS::AccountId}:function:${{self:custom.prefix}}*
    - Effect: Allow
      Action:
        - 's3:ListBucket'
      Resource:
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: PublicConfBucket
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: ObjectsBucket
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: SecretsBucket
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: ServerlessDeploymentBucket
    - Effect: Allow
      Action:
        - 's3:PutObject'
        - 's3:PutObjectAcl'
        - 's3:GetObject'
        - 's3:HeadObject'
      Resource:
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: PublicConfBucket
              - /*
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: ObjectsBucket
              - /*
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: SecretsBucket
              - /*
        - 'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: ServerlessDeploymentBucket
    - Effect: Allow
      Action:
        - 's3:GetBucketLocation'
        - 's3:ListAllMyBuckets'
      Resource: 'arn:aws:s3:::*'
    - Effect: Allow
      Action:
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'iot:Connect'
        - 'iot:Subscribe'
        - 'iot:Publish'
        - 'iot:Receive'
        - 'iot:DescribeEndpoint'
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - 'sts:AssumeRole'
      Resource:
        - 'Fn::GetAtt':
            - IotClientRole
            - Arn
    - Effect: Allow
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource: '*'
    - Effect: Allow
      Sid: AllowCloudFrontUpdateDistribution
      Action:
        - 'cloudfront:updateDistribution'
      Resource:
        - '*'
functions:
  preauth:
    handler: project/lib/lambda/http/preauth.handler
    memorySize: 1024
    events:
      - http:
          path: tradle/preauth
          method: post
          cors: true
  auth:
    handler: project/lib/lambda/http/auth.handler
    memorySize: 1024
    events:
      - http:
          path: tradle/auth
          method: post
          cors: true
  inbox2events:
    handler: project/lib/lambda/inbox-events.handler
    memorySize: 512
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: TRIM_HORIZON
          arn:
            'Fn::GetAtt':
              - InboxTable
              - StreamArn
  outbox2events:
    handler: project/lib/lambda/outbox-events.handler
    memorySize: 512
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: TRIM_HORIZON
          arn:
            'Fn::GetAtt':
              - OutboxTable
              - StreamArn
  seal2events:
    handler: project/lib/lambda/seal-events.handler
    memorySize: 512
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: TRIM_HORIZON
          arn:
            'Fn::GetAtt':
              - SealsTable
              - StreamArn
  onconnect:
    handler: project/lib/lambda/mqtt/onconnect.handler
    events:
      - iot:
          sql: 'SELECT * FROM ''$aws/events/presence/connected/#'''
  ondisconnect:
    handler: project/lib/lambda/mqtt/ondisconnect.handler
    events:
      - iot:
          sql: 'SELECT * FROM ''$aws/events/presence/disconnected/#'''
  onsubscribe:
    handler: project/lib/lambda/mqtt/onsubscribe.handler
    memorySize: 1024
    events:
      - iot:
          sql: 'SELECT * FROM ''$aws/events/subscriptions/subscribed/#'''
  onmessage:
    handler: project/lib/lambda/mqtt/onmessage.handler
    memorySize: 1024
    events:
      - iot:
          sql: >-
            SELECT * as data, clientid() as clientId FROM
            '${{self:custom.topicPrefix}}message'
  onmessage_http:
    handler: project/lib/lambda/http/onmessage.handler
    memorySize: 1024
    events:
      - http:
          path: tradle/message
          method: put
          cors: true
  send:
    handler: project/lib/lambda/send.handler
    memorySize: 1024
  bot_onmessage:
    handler: project/samplebot/index.onmessage
    memorySize: 1024
  bot_onsealevent:
    handler: project/samplebot/index.onsealevent
    memorySize: 1024
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: TRIM_HORIZON
          arn:
            'Fn::GetAtt':
              - SealsTable
              - StreamArn
  identity:
    handler: project/lib/lambda/identity.handler
  setenvvars:
    handler: project/lib/lambda/setenvvars.handler
    description:
      Ref: 'AWS::StackId'
  info:
    handler: project/lib/lambda/info.handler
    memorySize: 256
    events:
      - http:
          path: tradle/info
          method: get
          cors: true
  faucet_bitcoin:
    handler: project/lib/lambda/faucet-bitcoin.withdraw
  recharge:
    handler: project/lib/lambda/recharge.handler
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: false
  sealpending:
    handler: project/lib/lambda/sealpending.handler
    memorySize: 1024
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: false
  pollchain:
    handler: project/lib/lambda/pollchain.handler
    memorySize: 1024
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: false
resources:
  Resources:
    ObjectsBucket:
      Type: 'AWS::S3::Bucket'
      Description: content-addressed storage for all objects
    SecretsBucket:
      Type: 'AWS::S3::Bucket'
      Description: stuff
    PublicConfBucket:
      Type: 'AWS::S3::Bucket'
      Description: 'public configuration, e.g. identity, styles, logo, etc.'
    EventsTable:
      Type: 'AWS::DynamoDB::Table'
      Description: source of truth
      Properties:
        TableName: '${{self:custom.tables.events}}'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    PubKeysTable:
      Type: 'AWS::DynamoDB::Table'
      Description: maps pub keys to identities
      Properties:
        TableName: '${{self:custom.tables.pubkeys}}'
        AttributeDefinitions:
          - AttributeName: pub
            AttributeType: S
          - AttributeName: permalink
            AttributeType: S
        KeySchema:
          - AttributeName: pub
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: permalink
            KeySchema:
              - AttributeName: permalink
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - link
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    InboxTable:
      Type: 'AWS::DynamoDB::Table'
      Description: inbound messages from users
      Properties:
        TableName: '${{self:custom.tables.inbox}}'
        AttributeDefinitions:
          - AttributeName: author
            AttributeType: S
          - AttributeName: link
            AttributeType: S
          - AttributeName: time
            AttributeType: 'N'
        KeySchema:
          - AttributeName: author
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          - IndexName: link
            KeySchema:
              - AttributeName: link
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    OutboxTable:
      Type: 'AWS::DynamoDB::Table'
      Description: outbound messages to users
      Properties:
        TableName: '${{self:custom.tables.outbox}}'
        AttributeDefinitions:
          - AttributeName: recipient
            AttributeType: S
          - AttributeName: time
            AttributeType: 'N'
        KeySchema:
          - AttributeName: recipient
            KeyType: HASH
          - AttributeName: time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    SealsTable:
      Type: 'AWS::DynamoDB::Table'
      Description: blockchain seals for objects
      Properties:
        TableName: '${{self:custom.tables.seals}}'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: address
            AttributeType: S
          - AttributeName: unconfirmed
            AttributeType: S
          - AttributeName: unsealed
            AttributeType: S
          - AttributeName: link
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          - IndexName: unconfirmed
            KeySchema:
              - AttributeName: unconfirmed
                KeyType: HASH
              - AttributeName: address
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: unsealed
            KeySchema:
              - AttributeName: unsealed
                KeyType: HASH
              - AttributeName: address
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: link
            KeySchema:
              - AttributeName: link
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Description: per-user state objects
      Properties:
        TableName: '${{self:custom.tables.users}}'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    PresenceTable:
      Type: 'AWS::DynamoDB::Table'
      Description: maps ephemeral mqtt client ids to identity permalinks
      Properties:
        TableName: '${{self:custom.tables.presence}}'
        AttributeDefinitions:
          - AttributeName: clientId
            AttributeType: S
          - AttributeName: permalink
            AttributeType: S
        KeySchema:
          - AttributeName: permalink
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    IotClientRole:
      Type: 'AWS::IAM::Role'
      Description: role assumed by every connecting client
      Properties:
        RoleName: '${{self:custom.rolePrefix}}IotClientRole'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                AWS:
                  - 'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:root'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: IotClientRole
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:*'
                  Resource:
                    - 'Fn::Sub': >-
                        arn:aws:dynamodb:${{self:custom.region}}:${AWS::AccountId}:table/PresenceTable
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogGroup'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                  Resource: 'arn:aws:logs:::log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - 'iot:Connect'
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - 'iot:Publish'
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - 'iot:Subscribe'
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - 'iot:Receive'
                  Resource:
                    - '*'
  Outputs:
    ObjectsBucket:
      Description: content-addressed storage for all objects
      Value:
        Ref: ObjectsBucket
    SecretsBucket:
      Description: stuff
      Value:
        Ref: SecretsBucket
    PublicConfBucket:
      Description: 'public configuration, e.g. identity, styles, logo, etc.'
      Value:
        Ref: PublicConfBucket
    EventsTable:
      Description: source of truth
      Value:
        Ref: EventsTable
    PubKeysTable:
      Description: maps pub keys to identities
      Value:
        Ref: PubKeysTable
    InboxTable:
      Description: inbound messages from users
      Value:
        Ref: InboxTable
    OutboxTable:
      Description: outbound messages to users
      Value:
        Ref: OutboxTable
    SealsTable:
      Description: blockchain seals for objects
      Value:
        Ref: SealsTable
    UsersTable:
      Description: per-user state objects
      Value:
        Ref: UsersTable
    PresenceTable:
      Description: maps ephemeral mqtt client ids to identity permalinks
      Value:
        Ref: PresenceTable
    IotClientRole:
      Description: role assumed by every connecting client
      Value:
        Ref: IotClientRole
    ServerlessDeploymentBucket:
      Value:
        Ref: ServerlessDeploymentBucket
