AWSTemplateFormatVersion: '2010-09-09'
Description: MyCloud buckets

Parameters:
  ExistingObjectsBucket:
    Type: String
    Default: ""

  ExistingSecretsBucket:
    Type: String
    Default: ""

  ExistingPrivateConfBucket:
    Type: String
    Default: ""

  ExistingFileUploadBucket:
    Type: String
    Default: ""

  ExistingLogsBucket:
    Type: String
    Default: ""

  ExistingDeploymentBucket:
    Type: String
    Default: ""

  LogsDaysBeforeTransitionToGlacier:
    Type: Number

Conditions:
  CreateObjectsBucket:
    Fn::Equals: [ Ref: ExistingObjectsBucket, ""]
  CreateSecretsBucket:
    Fn::Equals: [ Ref: ExistingSecretsBucket, ""]
  CreatePrivateConfBucket:
    Fn::Equals: [ Ref: ExistingPrivateConfBucket, ""]
  CreateFileUploadBucket:
    Fn::Equals: [ Ref: ExistingFileUploadBucket, ""]
  CreateLogsBucket:
    Fn::Equals: [ Ref: ExistingLogsBucket, ""]
  CreateDeploymentBucket:
    Fn::Equals: [ Ref: ExistingDeploymentBucket, ""]

Resources:
  Objects:
    Condition: CreateObjectsBucket
    Type: AWS::S3::Bucket
    Description: content-addressed storage for all objects
    # DeletionPolicy: Retain

  Secrets:
    Condition: CreateSecretsBucket
    Type: AWS::S3::Bucket
    Description: stuff
    # DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  PrivateConf:
    Condition: CreatePrivateConfBucket
    Type: AWS::S3::Bucket
    Description: private configuration files
    # DeletionPolicy: Retain
    Properties:
      VersioningConfiguration:
        Status: Enabled

  FileUpload:
    Condition: CreateFileUploadBucket
    Type: AWS::S3::Bucket
    Description: file upload destination for all users
    # DeletionPolicy: Retain
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            MaxAge: 3600

  Logs:
    Condition: CreateLogsBucket
    Type: AWS::S3::Bucket
    Description: logs from lambda functions, apigateway and others
    # DeletionPolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: TransitionLogsToGlacier
            Prefix: glacier
            Status: Enabled
            Transitions:
              - TransitionInDays:
                  Ref: LogsDaysBeforeTransitionToGlacier
                StorageClass: Glacier

  Deployment:
    Condition: CreateDeploymentBucket
    Type: AWS::S3::Bucket
    Description: deployment storage bucket
    # DeletionPolicy: Retain

Outputs:
  Objects:
    Value:
      Fn::If:
      - CreateObjectsBucket
      - Ref: Objects
      - Ref: ExistingObjectsBucket

  Secrets:
    Value:
      Fn::If:
      - CreateSecretsBucket
      - Ref: Secrets
      - Ref: ExistingSecretsBucket

  PrivateConf:
    Value:
      Fn::If:
      - CreatePrivateConfBucket
      - Ref: PrivateConf
      - Ref: ExistingPrivateConfBucket

  FileUpload:
    Value:
      Fn::If:
      - CreateFileUploadBucket
      - Ref: FileUpload
      - Ref: ExistingFileUploadBucket

  Logs:
    Value:
      Fn::If:
      - CreateLogsBucket
      - Ref: Logs
      - Ref: ExistingLogsBucket

  Deployment:
    Value:
      Fn::If:
      - CreateDeploymentBucket
      - Ref: Deployment
      - Ref: ExistingDeploymentBucket

  StackName:
    Value:
      Ref: AWS::StackName

  StackId:
    Value:
      Ref: AWS::StackId
