version: '2.1'

services:
  dynamo:
    image: aaronshaf/dynamodb-admin
    # dummy credentials
    ports:
      - ${DYNAMO_ADMIN_PORT}:8001
    environment:
      - AWS_ACCESS_KEY_ID=mykey
      - AWS_SECRET_ACCESS_KEY=mysecret
      - DYNAMO_ENDPOINT=http://localstack:4569
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
